# Chapter 2: It starts with a tensor

## 2.1 Tensor fundamentals

We define a list with three numbers.

In [1]:
a = [1.0, 2.0, 1.0]

The first number can be accessed via index 0.

In [2]:
a[0]

1.0

We can update the third number via index 2.

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

We import the torch library.

In [4]:
import torch # <1>

We create a torch wth 3 ones.

In [5]:
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

We access index 1.

In [6]:
a[1]

tensor(1.)

We access the 1 index of the tensor and convert the value to a float.

In [7]:
float(a[1])

1.0

We access index 2 of the tensor and set it to 2.0.

In [8]:
a[2] = 2.0
a

tensor([1., 1., 2.])

We initialize a tensor to zero and manually set each value.

In [9]:
points = torch.zeros(6) # <1>
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

We initialize a tensor with a list of values.

In [10]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

We convert index 0 and 1 to floats.

In [11]:
float(points[0]), float(points[1])

(4.0, 1.0)

We create a multi-dimensional tensor.

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

We call the `shape` property of the tensor.

In [13]:
points.shape

torch.Size([3, 2])

We initialize a multi-dimensional tensor with zeros.

In [14]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

We intialize a multi-dimensional tensor with lists of values.

In [15]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

We can access the 2 element of the first list as follows:

In [16]:
points[0, 1]

tensor(1.)

We can access the first element as follows:

In [17]:
points[0]

tensor([4., 1.])

##  2.2 Tensors and storages

We initialize a multi-dimentional tensor with lists of values and call the `storage()` method.

In [18]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

We save the return value of the `storage()` method and access index 0.

In [19]:
points_storage = points.storage()
points_storage[0]

4.0

We access index 1 of the return value of the `storage()` method.

In [20]:
points.storage()[1]

1.0

Because tensors are views over a storage instance, changing the value of index 0 via `points_storage` also changes `points`.

In [21]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

## 2.3 Size, storage offset, and strides

Tensor views are defined by size, storage offset, and stride. Below, we print out the size, storage offset, and stride of a tensor.

In [22]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

Note, size and shape are the same.

In [23]:
second_point.size()

torch.Size([2])

In [24]:
second_point.shape

torch.Size([2])

In [25]:
points.stride()

(2, 1)

We select a subset of the original points tensor and print its size, storage_offset, and stride.

In [26]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [27]:
second_point.storage_offset()

2

In [28]:
second_point.stride()

(1,)

Changing the `second_point` tensor changes the `points` sensor because the storage is shared.

In [29]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

We can use the `clone()` method to duplicate the storage. After calling `clone()`, points and second_point do not share the same storage.

In [30]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

We can transpose a tensor by using the `t()` method.

In [31]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [32]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

The storage remains the same between `points` and `points_t`.

In [33]:
id(points.storage()) == id(points_t.storage())

True

The `stride()` is different between `points` and `points_t`.

In [34]:
points.stride()

(2, 1)

In [35]:
points_t.stride()

(1, 2)

For a multi-dimensionional array, we can specify the two dimensions along which transposing (i.e. flipping shape and stride) should occur.

In [36]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [37]:
transpose_t.shape

torch.Size([5, 4, 3])

In [38]:
some_t.stride()

(20, 5, 1)

In [39]:
transpose_t.stride()

(1, 5, 20)

A tensor whose values are laid out in the storage starting from the rightmost dimension onward (moving along rows for a 2D tensor, for example) is defined as being contiguous. Contiguous tensors are convenient because you can visit them efficiently and in order without jumping around in the storage.

In [40]:
points.is_contiguous()

True

In [41]:
points_t.is_contiguous()

False

You can obtain a new contiguous tensor from a noncontiguous one by using the `contiguous()` method.

In [42]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [43]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [44]:
points_t.stride()

(1, 2)

In [45]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [46]:
points_t_cont.stride()

(3, 1)

In [47]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

## 2.4 Numeric types

In [48]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [49]:
short_points.dtype

torch.int16

In [50]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [51]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [52]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

## 2.5 Indexing tensors

In [53]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [54]:
some_list = list(range(6))
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:-1]   # <5>
some_list[1:4:2] # <6>

[1, 3]

In [55]:
points[1:]       # <1>
points[1:, :]    # <2>
points[1:, 0]    # <3>
points[None]     # <4>

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

## 2.6 NumPy interoperability

In [57]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [58]:
points = torch.from_numpy(points_np)

## 2.7 Serializing tensors

In [61]:
torch.save(points, '../data/p1ch3/ourpoints.t')

In [62]:
with open('../data/p1ch3/ourpoints.t','wb') as f:
   torch.save(points, f)

In [63]:
points = torch.load('../data/p1ch3/ourpoints.t')

In [64]:
with open('../data/p1ch3/ourpoints.t','rb') as f:
   points = torch.load(f)

In [65]:
import h5py

f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [66]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [67]:
last_points = torch.from_numpy(dset[-2:])
f.close()

## 2.8 Moving tensors to the GPU

In [69]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [70]:
points_gpu = points.to(device='cuda')

In [71]:
points_gpu = points.to(device='cuda:0')

In [72]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device='cuda')  # <2>

In [73]:
points_gpu = points_gpu + 4

In [74]:
points_cpu = points_gpu.to(device='cpu')

In [75]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

## 2.9 The tensor API

In [77]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [78]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [79]:
a = torch.ones(3, 2)

In [80]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])